server:
  port: 8080

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: myUser
    password: kabulatka228

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

test:
  mode: false

logging:
  level:
    root: info